//! `acn loop run` (LOOP-10, LOOP-11, LOOP-14) under the CLI contract (CON-8):
//! a loop on the mock's embedded profiles, its regeneration from the report,
//! and refusals, each one JSON object on stdout with the exit code it implies.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)] // CON-19: tests are exempt

use std::path::Path;
use std::process::Command;

const HYP: &str = r#"[poc]
id = "zz"
title = "tool order and the cache"

[hypothesis]
statement = "A stable tool order moves the cached-token ratio."

[varies]
tool_order_stable = { kind = "bool" }

[measures]
primary = ["cached_token_ratio"]
secondary = ["ttft_p50_ms"]

[control]
description = "the shipped default"
config = { tool_order_stable = true }

[design]
search = "grid"
replicates = 4
twin_required = false

[falsifier]
predicate = "max_over_knobs(abs(effect(cached_token_ratio))) < 0.001"
inconclusive_if = "replicates < 4"

[expected]
outcome = "pass"
"#;

fn acn_in(dir: &Path, args: &[&str]) -> (Option<i32>, serde_json::Value) {
    let out = Command::new(env!("CARGO_BIN_EXE_acn"))
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap();
    let text = String::from_utf8(out.stdout).unwrap();
    assert_eq!(text.lines().count(), 1, "one JSON object: {text}");
    (
        out.status.code(),
        serde_json::from_str(text.trim()).unwrap(),
    )
}

/// Cites: LOOP-10, LOOP-11, LOOP-14, CON-8
#[test]
fn loop_run_and_its_regeneration_print_one_object_each() {
    let dir = tempfile::tempdir().unwrap();
    let d = dir.path();
    std::fs::write(d.join("zz.toml"), HYP).unwrap();
    std::fs::copy(
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../workloads/harness-smoke.toml"
        ),
        d.join("w.toml"),
    )
    .unwrap();
    let run = [
        "loop",
        "run",
        "--hypothesis",
        "zz.toml",
        "--workload",
        "w.toml",
        "--model",
        "mock-auto",
        "--budget",
        "10",
    ];
    let (code, j) = acn_in(d, &run);
    assert_eq!(code, Some(0), "{j}");
    assert_eq!(j["ok"], true);
    assert_eq!(j["stop"], "exhausted");
    assert_eq!(j["run_ids"].as_array().unwrap().len(), 3);
    let loop_id = j["loop_id"].as_str().unwrap();
    let report = j["report"].as_str().unwrap();
    assert!(
        report.ends_with(&format!("runs/loop/{loop_id}/report.json")),
        "{report}"
    );
    assert!(
        d.join("runs/verdicts")
            .join(j["verdict_id"].as_str().unwrap())
            .join("verdict.json")
            .exists()
    );
    let r: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(report).unwrap()).unwrap();
    // The binary's own identity (CON-31) is what the report records.
    let (_, v) = acn_in(d, &["version"]);
    assert_eq!(r["build_hash"], v["build_hash"]);
    assert_eq!(r["engine_hash"], v["engine_hash"]);

    // Regenerated byte for byte (LOOP-14).
    let (code, g) = acn_in(d, &["loop", "run", "--from-report", report]);
    assert_eq!(code, Some(0), "{g}");
    assert_eq!(
        (g["ok"].clone(), g["identical"].clone()),
        (true.into(), true.into())
    );
    assert!(
        g["dir"]
            .as_str()
            .unwrap()
            .ends_with(&format!("runs/regen/{loop_id}/1")),
        "{g}"
    );
    // A rendering that no longer matches: ok is false, exit 1 (CON-8).
    std::fs::write(d.join(format!("runs/loop/{loop_id}/report.md")), "edited\n").unwrap();
    let (code, g) = acn_in(d, &["loop", "run", "--from-report", report]);
    assert_eq!(code, Some(1), "{g}");
    assert_eq!(g["ok"], false);
    assert_eq!(g["differ"], serde_json::json!(["report.md"]));

    // Refused: an existing report, and a model that is no mock profile.
    let (code, e) = acn_in(d, &run);
    assert_eq!(
        (code, e["code"].as_str()),
        (Some(1), Some("loop_exists")),
        "{e}"
    );
    let mut bad = run;
    bad[7] = "mock-nope";
    let (code, e) = acn_in(d, &bad);
    assert_eq!(
        (code, e["code"].as_str()),
        (Some(1), Some("unknown_model")),
        "{e}"
    );
    // --from-report takes nothing else.
    let (code, e) = acn_in(
        d,
        &["loop", "run", "--from-report", report, "--budget", "3"],
    );
    assert_eq!(code, Some(1), "{e}");
    assert_eq!(e["ok"], false);
}
